In [1]:
import pandas as pd

In [2]:
data = pd.read_csv("teams.csv")

In [3]:
data.head()

team  year  athletes  events   age  height  weight  prev_medals  medals
0  AFG  1964         8       8  22.0   161.0    64.2          0.0       0
1  AFG  1968         5       5  23.2   170.2    70.0          0.0       0
2  AFG  1972         8       8  29.0   168.3    63.8          0.0       0
3  AFG  1980        11      11  23.6   168.4    63.2          0.0       0
4  AFG  2004         5       5  18.6   170.8    64.8          0.0       0

In [ ]:
data["medals"].value_counts()

In [5]:
x = data[["athletes", "prev_medals"]]

In [19]:
X = data[["athletes", "prev_medals"]]

In [6]:
y = data[["medals"]]

In [7]:
x["intercept"] = 1

<ipython-input-7-9582fd6e0245>:1: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  x["intercept"] = 1


In [8]:
x

athletes  prev_medals  intercept
0            8          0.0          1
1            5          0.0          1
2            8          0.0          1
3           11          0.0          1
4            5          0.0          1
...        ...          ...        ...
2009        26          0.0          1
2010        14          0.0          1
2011        16          3.0          1
2012         9          4.0          1
2013        31          0.0          1

[2014 rows x 3 columns]

In [9]:
x_T = x.T

In [10]:
x_T

0     1     2     3     4     5     6     7     8     9     ...  \
athletes      8.0   5.0   8.0  11.0   5.0   4.0   6.0   3.0   4.0   5.0  ...   
prev_medals   0.0   0.0   0.0   0.0   0.0   0.0   1.0   1.0   0.0   0.0  ...   
intercept     1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  ...   

             2004  2005  2006  2007  2008  2009  2010  2011  2012  2013  
athletes     52.0  20.0  47.0  28.0  21.0  26.0  14.0  16.0   9.0  31.0  
prev_medals   0.0  15.0   0.0   0.0   0.0   0.0   0.0   3.0   4.0   0.0  
intercept     1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0   1.0  

[3 rows x 2014 columns]

In [11]:
import numpy as np

In [13]:
o = np.linalg.inv(x_T @ x) @ x_T @ y

In [14]:
o.index = x.columns

In [15]:
o

medals
athletes     0.071112
prev_medals  0.734137
intercept   -1.961889

In [16]:
predictions = x @ o

In [17]:
predictions

medals
0    -1.392992
1    -1.606329
2    -1.392992
3    -1.179656
4    -1.606329
...        ...
2009 -0.112974
2010 -0.966319
2011  1.378315
2012  1.614667
2013  0.242587

[2014 rows x 1 columns]

In [18]:
from sklearn.linear_model import LinearRegression

model = LinearRegression()

In [20]:
model.fit(X,y)

LinearRegression()

In [22]:
model.intercept_

array([-1.96188939])

In [23]:
model.coef_

array([[0.07111214, 0.73413679]])

In [21]:
model.predict(X)

array([[-1.39299224],
       [-1.60632867],
       [-1.39299224],
       ...,
       [ 1.3783153 ],
       [ 1.61466709],
       [ 0.24258707]])

In [25]:
from sklearn.linear_model import Ridge, Lasso