In [1]:
import pandas as pd
import numpy as np

In [26]:
data = pd.read_csv("heart.csv")

In [9]:
data.head()

Pregnancies  Glucose  BloodPressure  SkinThickness  Insulin   BMI  \
0            6      148             72             35        0  33.6   
1            1       85             66             29        0  26.6   
2            8      183             64              0        0  23.3   
3            1       89             66             23       94  28.1   
4            0      137             40             35      168  43.1   

   DiabetesPedigreeFunction  Age  Outcome  
0                     0.627   50        1  
1                     0.351   31        0  
2                     0.672   32        1  
3                     0.167   21        0  
4                     2.288   33        1

In [6]:
data = pd.read_csv("cardata.csv")

In [7]:
data.head()

Car_Name  Year  Selling_Price  Present_Price  Kms_Driven Fuel_Type  \
0     ritz  2014           3.35           5.59       27000    Petrol   
1      sx4  2013           4.75           9.54       43000    Diesel   
2     ciaz  2017           7.25           9.85        6900    Petrol   
3  wagon r  2011           2.85           4.15        5200    Petrol   
4    swift  2014           4.60           6.87       42450    Diesel   

  Seller_Type Transmission  Owner  
0      Dealer       Manual      0  
1      Dealer       Manual      0  
2      Dealer       Manual      0  
3      Dealer       Manual      0  
4      Dealer       Manual      0

In [27]:
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [28]:
data["chol"].min()

126

In [29]:
data["chol"].max()

564

In [18]:
from sklearn.preprocessing import MinMaxScaler

MM_scaler = MinMaxScaler()

In [21]:
data["chol"] = MM_scaler.fit_transform(data[["chol"]])

In [22]:
data.head()

age  sex  cp  trestbps      chol  fbs  restecg  thalach  exang  oldpeak  \
0   52    1   0       125  0.196347    0        1      168      0      1.0   
1   53    1   0       140  0.175799    1        0      155      1      3.1   
2   70    1   0       145  0.109589    0        1      125      1      2.6   
3   61    1   0       148  0.175799    0        1      161      0      0.0   
4   62    0   0       138  0.383562    1        1      106      0      1.9   

   slope  ca  thal  target  
0      2   2     3       0  
1      0   0     3       0  
2      0   0     3       0  
3      2   1     3       0  
4      1   3     2       0

In [23]:
data["chol"].min()

0.0

In [24]:
data["chol"].max()

0.9999999999999998

In [25]:
data["chol"].mean()

0.273972602739726

In [30]:
data.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   52    1   0       125   212    0        1      168      0      1.0      2   
1   53    1   0       140   203    1        0      155      1      3.1      0   
2   70    1   0       145   174    0        1      125      1      2.6      0   
3   61    1   0       148   203    0        1      161      0      0.0      2   
4   62    0   0       138   294    1        1      106      0      1.9      1   

   ca  thal  target  
0   2     3       0  
1   0     3       0  
2   0     3       0  
3   1     3       0  
4   3     2       0

In [31]:
data["chol"].mean()

246.0

In [32]:
data["chol"].std()

51.59251020618206

In [33]:
from sklearn.preprocessing import StandardScaler

ss_scaler = StandardScaler()

In [34]:
data["chol"] = ss_scaler.fit_transform(data[['chol']])

In [35]:
data.head()

age  sex  cp  trestbps      chol  fbs  restecg  thalach  exang  oldpeak  \
0   52    1   0       125 -0.659332    0        1      168      0      1.0   
1   53    1   0       140 -0.833861    1        0      155      1      3.1   
2   70    1   0       145 -1.396233    0        1      125      1      2.6   
3   61    1   0       148 -0.833861    0        1      161      0      0.0   
4   62    0   0       138  0.930822    1        1      106      0      1.9   

   slope  ca  thal  target  
0      2   2     3       0  
1      0   0     3       0  
2      0   0     3       0  
3      2   1     3       0  
4      1   3     2       0

In [37]:
data["chol"].mean()

-3.4660621256590253e-18

In [38]:
data["chol"].std()

1.0004881620988826

In [39]:
from sklearn.preprocessing import RobustScaler

In [40]:
data.head()

age  sex  cp  trestbps      chol  fbs  restecg  thalach  exang  oldpeak  \
0   52    1   0       125 -0.659332    0        1      168      0      1.0   
1   53    1   0       140 -0.833861    1        0      155      1      3.1   
2   70    1   0       145 -1.396233    0        1      125      1      2.6   
3   61    1   0       148 -0.833861    0        1      161      0      0.0   
4   62    0   0       138  0.930822    1        1      106      0      1.9   

   slope  ca  thal  target  
0      2   2     3       0  
1      0   0     3       0  
2      0   0     3       0  
3      2   1     3       0  
4      1   3     2       0

In [41]:
x = data.drop(["target"], axis=1)

In [42]:
y = data.target

In [43]:
y

0       0
1       0
2       0
3       0
4       0
       ..
1020    1
1021    0
1022    0
1023    1
1024    0
Name: target, Length: 1025, dtype: int64

In [44]:
x

age  sex  cp  trestbps      chol  fbs  restecg  thalach  exang  oldpeak  \
0      52    1   0       125 -0.659332    0        1      168      0      1.0   
1      53    1   0       140 -0.833861    1        0      155      1      3.1   
2      70    1   0       145 -1.396233    0        1      125      1      2.6   
3      61    1   0       148 -0.833861    0        1      161      0      0.0   
4      62    0   0       138  0.930822    1        1      106      0      1.9   
...   ...  ...  ..       ...       ...  ...      ...      ...    ...      ...   
1020   59    1   1       140 -0.484803    0        1      164      1      0.0   
1021   60    1   0       125  0.232705    0        0      141      1      2.8   
1022   47    1   0       110  0.562371    0        0      118      1      1.0   
1023   50    0   0       110  0.155137    0        0      159      0      0.0   
1024   54    1   0       120 -1.124743    0        1      113      0      1.4   

      slope  ca  thal  
0         2   2     3  
1         0   0     3  
2         0   0     3  
3         2   1     3  
4         1   3     2  
...     ...  ..   ...  
1020      2   0     2  
1021      1   1     3  
1022      1   1     2  
1023      2   0     2  
1024      1   1     3  

[1025 rows x 13 columns]

In [45]:
scaled = ss_scaler.fit_transform(x)

In [47]:
scaled.shape

(1025, 13)

In [48]:
scaled

array([[-0.26843658,  0.66150409, -0.91575542, ...,  0.99543334,
         1.20922066,  1.08985168],
       [-0.15815703,  0.66150409, -0.91575542, ..., -2.24367514,
        -0.73197147,  1.08985168],
       [ 1.71659547,  0.66150409, -0.91575542, ..., -2.24367514,
        -0.73197147,  1.08985168],
       ...,
       [-0.81983438,  0.66150409, -0.91575542, ..., -0.6241209 ,
         0.23862459, -0.52212231],
       [-0.4889957 , -1.51170646, -0.91575542, ...,  0.99543334,
        -0.73197147, -0.52212231],
       [-0.04787747,  0.66150409, -0.91575542, ..., -0.6241209 ,
         0.23862459,  1.08985168]])

In [49]:
x = pd.DataFrame(scaled, columns=x.columns)

In [50]:
x.head()

age       sex        cp  trestbps      chol       fbs   restecg  \
0 -0.268437  0.661504 -0.915755 -0.377636 -0.659332 -0.418878  0.891255   
1 -0.158157  0.661504 -0.915755  0.479107 -0.833861  2.387330 -1.004049   
2  1.716595  0.661504 -0.915755  0.764688 -1.396233 -0.418878  0.891255   
3  0.724079  0.661504 -0.915755  0.936037 -0.833861 -0.418878  0.891255   
4  0.834359 -1.511706 -0.915755  0.364875  0.930822  2.387330  0.891255   

    thalach     exang   oldpeak     slope        ca      thal  
0  0.821321 -0.712287 -0.060888  0.995433  1.209221  1.089852  
1  0.255968  1.403928  1.727137 -2.243675 -0.731971  1.089852  
2 -1.048692  1.403928  1.301417 -2.243675 -0.731971  1.089852  
3  0.516900 -0.712287 -0.912329  0.995433  0.238625  1.089852  
4 -1.874977 -0.712287  0.705408 -0.624121  2.179817 -0.522122

In [52]:
x["sex"].unique()

array([ 0.66150409, -1.51170646])

In [53]:
data = pd.read_csv("/content/titanic.csv")

In [54]:
data.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [59]:
data.dropna(inplace=True, axis=0)

In [60]:
data["Embarked"].unique()

array(['C', 'S', 'Q'], dtype=object)

In [61]:
data["Embarked"].value_counts()

S    116
C     65
Q      2
Name: Embarked, dtype: int64

In [62]:
from sklearn.preprocessing import OneHotEncoder

In [63]:
o_encoder = OneHotEncoder()

In [67]:
data["Embarked"]

1      C
3      S
6      S
10     S
11     S
      ..
871    S
872    S
879    C
887    S
889    C
Name: Embarked, Length: 183, dtype: object

In [66]:
o_encoder.fit_transform(data[["Embarked"]]).toarray()

array([[1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [1., 0., 0.],
       [1., 0., 0.],
       [1., 0., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 1., 0.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0., 1.],
       [0., 0

In [68]:
from sklearn.preprocessing import LabelEncoder

l_encoder = LabelEncoder()

In [70]:
data["Embarked"] = l_encoder.fit_transform(data[["Embarked"]])

/usr/local/lib/python3.10/dist-packages/sklearn/preprocessing/_label.py:116: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().
  y = column_or_1d(y, warn=True)


In [71]:
data.head()

PassengerId  Survived  Pclass  \
1             2         1       1   
3             4         1       1   
6             7         0       1   
10           11         1       3   
11           12         1       1   

                                                 Name     Sex   Age  SibSp  \
1   Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
3        Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
6                             McCarthy, Mr. Timothy J    male  54.0      0   
10                    Sandstrom, Miss. Marguerite Rut  female   4.0      1   
11                           Bonnell, Miss. Elizabeth  female  58.0      0   

    Parch    Ticket     Fare Cabin  Embarked  
1       0  PC 17599  71.2833   C85         0  
3       0    113803  53.1000  C123         2  
6       0     17463  51.8625   E46         2  
10      1   PP 9549  16.7000    G6         2  
11      0    113783  26.5500  C103         2

In [72]:
data["Embarked"].value_counts()

2    116
0     65
1      2
Name: Embarked, dtype: int64