In [30]:
!pip install numpy

Looking in indexes: https://pypi.org/simple, https://us-python.pkg.dev/colab-wheels/public/simple/


In [31]:
import numpy as np

In [32]:
x = [1,2,3,4,5]

In [33]:
y = np.array(x)
print(y)

[1 2 3 4 5]


In [34]:
print(type(y))

<class 'numpy.ndarray'>


In [35]:
print(type(x))

<class 'list'>


In [36]:
z = np.array(7)

In [37]:
print(z)

7


In [38]:
print(type(z))

<class 'numpy.ndarray'>


In [39]:
x = np.array([[1,2,3,4],[5,6,7,8]])

In [40]:
print(x)

[[1 2 3 4]
 [5 6 7 8]]


In [51]:
x = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

In [42]:
print(x)

[[[ 1  2  3]
  [ 4  5  6]]

 [[ 7  8  9]
  [10 11 12]]]


In [53]:
x[1,0,1]

8

In [43]:
x = np.array([1,2,3,4,5])

In [44]:
x[2]

3

In [47]:
x = np.array([[1,2,3,4],[5,6,7,8]])

In [48]:
x[1,1]

6

In [49]:
x[0,3]

4

In [56]:
oned = np.array([1,2,3,4,5,6,7,78])

oned[1:7]

array([2, 3, 4, 5, 6, 7])

In [57]:
twod = np.array([[1,2,3,4],[5,6,7,8]])

In [62]:
twod[0:2, 1:4]

array([[2, 3, 4],
       [6, 7, 8]])

In [60]:
twod[0, 1:5]

array([2, 3, 4])

In [61]:
twod[0:2, 1]

array([2, 6])

In [63]:
x = np.array([1,2,3,4,5])
y = x.copy()
z = x.view()

x[0] = 18

In [64]:
print(x)

[18  2  3  4  5]


In [65]:
print(y)

[1 2 3 4 5]


In [66]:
print(z)

[18  2  3  4  5]


In [67]:
print(z.shape)

(5,)


In [68]:
x = np.array([[1,2,3,4],[5,6,7,8]])

In [69]:
x.shape

(2, 4)

In [70]:
x = np.array([[[1,2,3], [4,5,6]], [[7,8,9], [10,11,12]]])

In [71]:
x.shape

(2, 2, 3)

In [73]:
x = np.array(["a", "b", "c", "d", "e", "f", "g", "h","i", "j"])
y = x.reshape(5,2)
y

array([['a', 'b'],
       ['c', 'd'],
       ['e', 'f'],
       ['g', 'h'],
       ['i', 'j']], dtype='<U1')

In [75]:
x = np.array(["a", "b", "c", "d", "e", "f", "g", "h","i", "j", "k", "l"])
y = x.reshape(2,3,2)
y

array([[['a', 'b'],
        ['c', 'd'],
        ['e', 'f']],

       [['g', 'h'],
        ['i', 'j'],
        ['k', 'l']]], dtype='<U1')

In [76]:
print(y)

[[['a' 'b']
  ['c' 'd']
  ['e' 'f']]

 [['g' 'h']
  ['i' 'j']
  ['k' 'l']]]


In [77]:
y.shape

(2, 3, 2)

In [78]:
z = y.reshape(-1)

In [79]:
print(z)
print(z.shape)

['a' 'b' 'c' 'd' 'e' 'f' 'g' 'h' 'i' 'j' 'k' 'l']
(12,)


In [83]:
for ele in z:
  print(ele)

a
b
c
d
e
f
g
h
i
j
k
l


In [86]:
x = np.array([[1,2,3,4],[5,6,7,8]])
for ele in x:
  print(ele)
  for element in ele:
    print(element)


[1 2 3 4]
1
2
3
4
[5 6 7 8]
5
6
7
8


In [87]:
x = np.array(["a", "b", "c", "d", "e", "f", "g", "h","i", "j", "k", "l"])
y = x.reshape(2,3,2)
y

array([[['a', 'b'],
        ['c', 'd'],
        ['e', 'f']],

       [['g', 'h'],
        ['i', 'j'],
        ['k', 'l']]], dtype='<U1')

In [91]:
for a in y:
  print(a)
  print("____")
  for b in a:
    print(b)
    print("---")
    for c in b:
      print(c)
      print("$$$")

[['a' 'b']
 ['c' 'd']
 ['e' 'f']]
____
['a' 'b']
---
a
$$$
b
$$$
['c' 'd']
---
c
$$$
d
$$$
['e' 'f']
---
e
$$$
f
$$$
[['g' 'h']
 ['i' 'j']
 ['k' 'l']]
____
['g' 'h']
---
g
$$$
h
$$$
['i' 'j']
---
i
$$$
j
$$$
['k' 'l']
---
k
$$$
l
$$$


In [92]:
for a in y:
  for b in a:
    for c in b:
      print(c)
  

a
b
c
d
e
f
g
h
i
j
k
l


In [93]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.concatenate((x,y))
z

array([1, 2, 3, 4, 5, 6])

In [95]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])
z = np.concatenate((x,y), axis=0)
z

array([[1, 2, 3],
       [4, 5, 6]])

In [96]:
x = np.array([[1,2,3]])
y = np.array([[4,5,6]])
z = np.concatenate((x,y), axis=1)
z

array([[1, 2, 3, 4, 5, 6]])

In [97]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.hstack((x,y))
z

array([1, 2, 3, 4, 5, 6])

In [98]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.vstack((x,y))
z

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.dstack((x,y))
z

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [100]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.hstack((x,y))
z

array([1, 2, 3, 4, 5, 6])

In [103]:
y = np.array_split(z, 3)

In [104]:
y

[array([1, 2]), array([3, 4]), array([5, 6])]

In [106]:
x = np.array([1,2,3])
y = np.array([4,5,6])
z = np.dstack((x,y))
z

array([[[1, 4],
        [2, 5],
        [3, 6]]])

In [107]:
x = np.array([[1,2], [3,4], [5,6], [7,8], [9,10],[11,12]])
y = np.array_split(x, 3)

In [108]:
y

[array([[1, 2],
        [3, 4]]), array([[5, 6],
        [7, 8]]), array([[ 9, 10],
        [11, 12]])]

In [111]:
x = np.array([[1,2], [3,4], [5,6], [7,8], [9,10],[11,12]])
y = np.array_split(x, 4, axis=1)
y

[array([[ 1],
        [ 3],
        [ 5],
        [ 7],
        [ 9],
        [11]]), array([[ 2],
        [ 4],
        [ 6],
        [ 8],
        [10],
        [12]]), array([], shape=(6, 0), dtype=int64), array([], shape=(6, 0), dtype=int64)]

In [112]:
x = np.array([[1,2], [3,4], [5,6], [7,8], [9,10],[11,12]])
h = np.hsplit(x,2)
print(h)

[array([[ 1],
       [ 3],
       [ 5],
       [ 7],
       [ 9],
       [11]]), array([[ 2],
       [ 4],
       [ 6],
       [ 8],
       [10],
       [12]])]


In [114]:
x = np.array([[1,2], [3,4], [5,6], [7,8], [9,10],[11,12]])
v = np.vsplit(x,2)
print(v)

[array([[1, 2],
       [3, 4],
       [5, 6]]), array([[ 7,  8],
       [ 9, 10],
       [11, 12]])]


In [115]:
a = np.array([[[1,2],[3,4],[5,6]], [[7,8],[9,10],[11,12]]])

In [116]:
d = np.dsplit(a, 2)

In [117]:
d

[array([[[ 1],
         [ 3],
         [ 5]],
 
        [[ 7],
         [ 9],
         [11]]]), array([[[ 2],
         [ 4],
         [ 6]],
 
        [[ 8],
         [10],
         [12]]])]

In [119]:
x = np.array([1,2,3,4,5,6,7,1,2,3])

In [122]:
y= np.where(x == 3)

In [123]:
print(y)

(array([2, 9]),)


In [124]:
x = np.array([3,532,2,313,5,772,3,34])
y = np.sort(x)
y

array([  2,   3,   3,   5,  34, 313, 532, 772])

In [125]:
x = np.array([[3,532,2,313],[5,772,3,34]])
y = np.sort(x)
y

array([[  2,   3, 313, 532],
       [  3,   5,  34, 772]])

In [126]:
x = np.zeros((4,5), dtype="i")
x

array([[0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0]], dtype=int32)

In [127]:
x = np.ones((2,5), dtype="i")
x

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]], dtype=int32)

In [129]:
x = np.full((12,5),5)
x

array([[5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5],
       [5, 5, 5, 5, 5]])

In [131]:
x = np.arange(2,10,3)
x

array([2, 5, 8])

In [132]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])
print(np.add(a,b))

[ 6  8 10 12]


In [133]:
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[-4 -4 -4 -4]
[ 5 12 21 32]
[0.2        0.33333333 0.42857143 0.5       ]


In [134]:
x = np.array([[1,2,3,4,5],[6,7,8,9,10]])
print(np.sum(x, axis=0))

[ 7  9 11 13 15]


In [135]:
print(np.sum(x, axis=1))

[15 40]


In [137]:
print(np.mean(x, axis=1))

[3. 8.]


In [138]:
print(np.mean(x, axis=0))

[3.5 4.5 5.5 6.5 7.5]


In [139]:
x = np.random.random((4,4))
x

array([[0.40369531, 0.34239921, 0.0145844 , 0.20481897],
       [0.03666259, 0.30558412, 0.31384668, 0.43502155],
       [0.26041184, 0.01805949, 0.21081191, 0.94810209],
       [0.41104924, 0.84412041, 0.82969086, 0.59518718]])

In [140]:
y = np.random.randint(10,100, (4,4))
y

array([[87, 61, 53, 64],
       [63, 51, 50, 27],
       [33, 27, 18, 74],
       [97, 36, 71, 64]])

In [141]:
x = np.linspace(10,30,5)
x

array([10., 15., 20., 25., 30.])